In [1]:
import numpy
import math

vertices = [(0,0),(0,1),(1,1),(1,0)]


new_vertex = ((vertices[0][0] + vertices[-1][0]) / 2, 
             (vertices[0][1] + vertices[-1][1]) / 2)


print(new_vertex)
angles=[]
for i, vertex in enumerate(vertices):
    print(i,vertices[i-1],vertices[(i+1)%len(vertices)])
    this_vertex = vertices[i]
    next_vertex = vertices[(i+1)%len(vertices)]
    previous_vertex = vertices[i-1]


    v1 = (next_vertex[0]-this_vertex[0],next_vertex[1]-this_vertex[1])
    v2 = (previous_vertex[0]-this_vertex[0],previous_vertex[1]-this_vertex[1])
    
    angles.append(math.degrees(math.acos(numpy.dot(v1,v2)/numpy.linalg.norm(v1)/numpy.linalg.norm(v2))))


print(angles)




(0.5, 0.0)
0 (1, 0) (0, 1)
1 (0, 0) (1, 1)
2 (0, 1) (1, 0)
3 (1, 1) (0, 0)
[90.0, 90.0, 90.0, 90.0]


AttributeError: module 'numpy' has no attribute 'rank'

In [ ]:
import math
origin=(0,0)
sides=3
vertices=[origin]
for i in range(1,sides):
    theta=math.radians(i*(180-360/sides))
    vertices.append((vertices[i-1][0]+math.cos(theta),vertices[i-1][1]+math.sin(theta)))
print(vertices)

In [ ]:
import math
theta=108*5
print(math.cos(math.radians(theta)),math.sin(math.radians(theta)))


In [ ]:
vertices = [(0,0),(0,1),(1,1),(1,0)]

#b = list(sum(vertices, ()))
#print(b)

sum(vertices,())

In [ ]:
class Contact(object):

    def __init__(self, first_name=None, last_name=None, 
                 display_name=None, email=None):
        self.first_name = first_name
        self.last_name = last_name
        self.display_name = display_name
        self.email = email

    def print_info(self):
        print (self.display_name, "<" + self.email + ">")            

    def set_email(self, value):
        if '@' not in value:
            raise Exception("This doesn't look like an email address.")
        self._email = value

    def get_email(self):
        return self._email

    email = property(get_email, set_email)

In [ ]:
c = Contact(email="t@f")
c.print_info()

In [ ]:
class TestChildren():

    def __init__(self,id="",children=None):
        self.id = id
        self.children = children
        

    def add_child(self,child):
        if self.children is None:
            self.children = [child]
        else:
            self.children.append(child)
        

    def __str__(self):
        if self.children is None:
            return f"{self.id} -> None"
        
        str_ids=[]
        for c in self.children:
            str_ids.append(c.id)

        return f"{self.id} -> {str_ids}"

    def list_all_children(self,level=0):
        list_of_children=""
        
        if self.children:
            for child in self.children:
                list_of_children += f"\n{'|'*(level != 0)}{'  '*level}{' '*(level > 1)}|--{child.list_all_children(level+1)}"
            return f"{self.id}{list_of_children}"
        else:
            return f"{self.id}"

lvl1 = TestChildren(id="lvl1")
lvl2 = TestChildren(id="lvl2")
top = TestChildren(id="top",children=[lvl1])
top.add_child(lvl2)
lvl1_3=TestChildren(id="lvl3")
lvl2.add_child(lvl1_3)
lvl1.add_child(lvl2)


print(top)
print(lvl1,lvl2)
print(top.list_all_children())

In [ ]:
print(f"{'|'*(True)}{' '*4} hell")

In [141]:
import random

rgb = random.choices(population=range(255),k=3)
rgb = tuple(map(lambda x: x/255,rgb))
print(rgb)

#rgb.append(0.1)


(0.9098039215686274, 0.12941176470588237, 0.5725490196078431)


In [14]:
import numpy

a = numpy.matrix([[1,4,7],[2,5,8],[3,6,9]])

print(f"rank: {numpy.linalg.matrix_rank(a)} of \n{a}")

b = numpy.matrix([[1,3,2],[3,9,6],[-2,-6,-4]])
print(numpy.linalg.matrix_rank(b))

c = numpy.matrix([[1,2,3],[0,4,5],[0,0,6]])
print(numpy.linalg.matrix_rank(c))

A = numpy.matrix([[1,3,7],[2,8,3],[7,8,1]])
print(numpy.linalg.matrix_rank(A))


rank: 2 of 
[[1 4 7]
 [2 5 8]
 [3 6 9]]
1
3
3
